### PR TITLE
[FEATURE 💡] Animate theme button 

### LINKED ISSUE #170: [FEATURE 💡] Animate theme button
### Description

Add animation in the theme toggle button

### Screenshots

_No response_

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by hardy07**
# Issue #170 📐

- I [Sakthivel](https://www.github.com/hardy07) have worked for #170

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #170

## Attachments📷

Here is a video of the animated toggle button that I have made 🔽

https://github.com/warmachine028/nike/assets/63062063/01bdaf7c-2ee3-4861-be78-0a9a5a258620

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
- Resolve the merge conflicts in `package-lock.json`

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Pull the latest changes from main into your fork to resolve the conflict

**Comment by hardy07** [comment]
sorry i closed the pr by mistake can you reopen it

**Comment by hardy07** [comment]
im having some difficulties I'll do it shortly

**Comment by hardy07** [comment]
does it fix the conflict? @warmachine028

**Pull request merged**
