### PR TITLE
fixes

### LINKED ISSUE #16: [FEATURE] Card Hover animations
### Description

- Add hover animations to these card components.
- A grow animation must be applied in the hovered card
- Do using Tailwind classes

### Screenshots

- Before
image

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by jakepears**
# Issue #16 📐

- **I Jake Pearson have worked for Issue #16**

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

**I accept the fact that i have followed the guidelines and have not copied the codes from around the internet**
:besides code from my own repos, which shouldn't count
- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- **My pull request closes #16**

  Also helped out to add some hover animations on other things; footer, buttons, and navbar. 
  
  
---

### CODE REVIEW

**Comment by warmachine028** [comment]
## @Jake great to see you made a contribution to this project. 
However you need to get assigned to the issue first, before contributing. This PR will be kept open. But you are to get assigned to the issue first.

**Comment by jakepears** [comment]
ok, do i have to resubmit the pull request? what do i redo on my end?

**Comment by warmachine028** [comment]
Get assigned to the issue

**Comment by warmachine028** [comment]
I really like the changes you made to this website, really impressive.

**Comment by jakepears** [comment]
> I really like the changes you made to the footer of this website, really impressive. 
thank you😛

**Comment by jakepears** [comment]
^ this pull requests consists of a few fixes on the hover activity, various typos, and working towards a cleaner experience. also added a hover animation to the social media buttons on the footer. thank you.

(i just needed a green dot on my github graph tbh)

**Comment by warmachine028** [comment]
### Congratulations 🎉 @jakepears on your first contribution in Nike

- Make sure to star this project, if you liked contributing to it. 🌟🌟🌟
- You can raise another new issue, if you find something is worth enhancement or needs a fix.
- You can see my other projects too, which you might feel appealing.
- You also follow me for making more future contributions in open source projects.

**Review by warmachine028 — COMMENTED** [review]
Approved

**Comment by jakepears** [comment]
Let me know what you think of my implementations. I could always use the boost I get for contributing, so if okay i'd like to keep adding features:)

**Pull request merged**
