### PR TITLE
Hamburger menu (not finished)

### PR DESCRIPTION
**Pull request by FranDiSilvestro**
# Issue #1 📐

- I Franco (https://github.com/FranDiSilvestro) have worked fo #1 

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

### CODE REVIEW

**Comment by FranDiSilvestro** [comment]
I did 3 things
I blocked the scrolling when the menu is opened
I disabled mouse events outside of the menu when it is opened
And i tried to fixed a bug but i wasnt capable, i will try later
The bug consistss on changing the menu context when the window width is grater than 1024, because if you have the menu open and resize the window to a value greater than 1024, you wont be able to scroll because the menu context is "open", if someone wants to help it would be welcomed

**Comment by warmachine028** [comment]
I will merge the 3 PR's you made into main, but I am worried about merge conflicts, so it would be easier for me to review everything in 1 PR if you could merge them

**Comment by FranDiSilvestro** [comment]
Hi @warmachine028, sorry I had busy days, i dont know how to merge them, can you help me?

**Comment by warmachine028** [comment]
I've already merged everything sequence wise

**Pull request merged**
