### PR TITLE
[FEATURE 💡] Make Navbar floating

### LINKED ISSUE #113: [FEATURE 💡] Make Navbar floating
### Description

- When we scroll down, the Navbar is not visible in the page
- Make the Icon a bit bigger
- Make the Navbar thinner than current
- Make the Navbar floating
- The floating Navbar should only be visible when scrolling up from anywhere it's not currently visible
- have a look at the [original website here](https://www.nike.com/sg/). Scroll down and observe the Navbar here

### Screenshots

- Original Website

Screenshot_2023-10-05-19-51-17-658_com android chrome

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by theDevSoham**
# Issue #113  📐

- I [theDevSoham](https://github.com/theDevSoham) have worked for #113 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #113 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

Screenshot from 2023-10-06 22-28-11
Screenshot from 2023-10-06 22-28-40
Screenshot from 2023-10-06 22-29-35
Screenshot from 2023-10-06 22-29-43
  
  
  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Can you make the logo a bit bigger and the Navbar a bit shorter like the original site

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Also the Navbar is nearly perfect except for one feature, if you see the original site the Navbar is hidden whenever we scroll down. However if we just scroll up a bit it becomes visible. Will it be possible for you to implement this? It would be a great value to this project. You can do some research around the internet

**Comment by theDevSoham** [comment]
Hey @warmachine028 I've implemented the requested changes. Can you please check and let me know if any further modifications are required? I've also increased the dimensions of the nav bar logo for mobile screen too. So please check the responsive screens also


Screenshot from 2023-10-07 12-24-20
Screenshot from 2023-10-07 12-24-54

**Review by warmachine028 — APPROVED** [review]
Splendid, you made a valuable contribution to this project

**Comment by theDevSoham** [comment]
@warmachine028 Thanks. Happy Hacktober [🎉](https://emojipedia.org/party-popper)

**Pull request merged**
