### PR TITLE
[DOCS 📄] Page link to icon

### LINKED ISSUE #77: [DOCS 📄] Page link to icon
### Description

- Currently on clicking the icon of README.md, it opens the icon itself.
- The link tag must be fixed to redirect to the original deployed Nike website.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Swarno-Coder**
# Issue #77  📐

- I [Swarno-Coder](https://github.com/Swarno-Coder/) have worked for #77 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #77 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

image
  
  
  
---

### CODE REVIEW

**Comment by warmachine028** [comment]
I can see a commit by @Anirudha0702 . 
Did you both work on this issue?

**Comment by Anirudha0702** [comment]
@warmachine028  YES WE DID

**Comment by warmachine028** [comment]
Alright assigning you both @Swarno-Coder, @Anirudha0702 , but I am not sure who will get the hacktoberfest tag accepted

**Comment by warmachine028** [comment]
## Changes LGTM, Merging it right away.
- Make sure to star this repo 🌟, if you liked contributing to it.
- Follow me for more such opportunities.

**Review by warmachine028 — APPROVED** [review]

**Comment by Swarno-Coder** [comment]
@warmachine028 The issue you mentioned has been fixed. Now, accept the MR to complete my hacktoberfest PR req

**Comment by warmachine028** [comment]
See if the Progress is showing in your profile now

**Comment by Swarno-Coder** [comment]
Thanks brother, now it's on the waiting period before acceptance.

**Pull request merged**
