### PR TITLE
[FIX 🛠️] Outdated Twitter Logo

### LINKED ISSUE #154: [BUG 🐞] Outdated Twitter Logo
### Description

The Twitter logo needs to to be updated to X.

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hanzalahwaheed**
# Issue #154 📐

- I [Hanzalah Waheed](https://github.com/hanzalahwaheed) have worked for #154 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #154 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

image

  
  
  
---

### CODE REVIEW

**Comment by warmachine028** [comment]
Update pr title
Fix your name in the PR template
See closed PRs for reference

**Comment by warmachine028** [comment]
Update pr title
Fix your name in the PR template
See closed PRs for reference

**Comment by hanzalahwaheed** [comment]
> Update pr title Fix your name in the PR template See closed PRs for reference

Made the changes. Hope all is good now!

**Comment by warmachine028** [comment]
Fix PR title

**Pull request merged**
