### PR TITLE
[BUG 🐞] Sign Up Input  # FIXED

### LINKED ISSUE #31: [BUG 🐞] Sign Up Input
### Description

- The sign up input doesn't feel accurate on dark modes.
- This needs to match the theme.

### Screenshots

image

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by mhamzanadeem**
# Issue #31 📐

I [M Hamza Nadeem](https://github.com/mhamzanadeem) have worked for #31

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #31

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

<attach screenshots here>

fggrgr

I made changes on line 15  of file Subscribe.jsx
  
  
  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Can you try this using tailwind, I'm sure there's a way to change the color instead of inline styles directly

**Comment by mhamzanadeem** [comment]
ok , i will try this with tailwind CSS

**Comment by mhamzanadeem** [comment]
I have made changes in  " mhamzanadeem:main" .  should I  make another pull request or you have recieved my changes ?

**Comment by warmachine028** [comment]
No no, it's visible and looking just like it's supposed to. Great work.

**Pull request merged**
