### PR TITLE
[FEATURE 💡] Some UI Improvements

### LINKED ISSUE #103: [FEATURE 💡] Some UI Improvements
### Description

In the current Version there are some small UI things. I am listing some of the UI faults:

1) In large screen formats, the Heading in the Hero section has no padding in the left:
To be Fixed:
UI fix

Fixed Changes:
fixed

2) In the Mobile Version the stats are not looking great aligning at the start, that can be improved by centering them

To be Fixed:
to be fixed

Fixed Changes:
mobile fix

3. The Current Hard Hover effect can be somewhat improved, shadows and border effects can be added to increase the interactivity experience.
shadow

Please Assign the Issue To me.

### Screenshots

_No response_

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by Keshav-Aneja**
# Issue #103 📐

- I [KeshavAneja](https://github.com/Keshav-Aneja) have worked for #103

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #103

### CODE REVIEW

**Comment by warmachine028** [comment]
Provide screenshots also in this PR

**Comment by warmachine028** [comment]
Rename PR title to Issue name as previous PR's

**Comment by Keshav-Aneja** [comment]
Here are the screenshots of the Changes Made:
a
b
[recording-2023-10-04-19-19-55.webm](https://github.com/warmachine028/nike/assets/119158790/781fce0e-04ef-457d-a3e9-b52bcf6f7cff)

**Comment by Keshav-Aneja** [comment]
> Rename PR title to Issue name as previous PR's

Done Sir

**Review by warmachine028 — APPROVED** [review]
Changes Lgtm

**Pull request merged**
