### PR TITLE
[FEATURE 💡] dark/light theme improvement

### LINKED ISSUE #105: [FEATURE 💡] dark/light theme improvement
### Description

- Inverted navbar background color theme (Picture 1, Picture 2)
- Some texts do not contrast when in a dark theme (Picture 3)
- Some UI doesn't have dark theme (Picture 4, Picture 5)
- Theme button icon only shows the same icon

I'm willing to work on it

### Screenshots

Picture 1 (light theme)
image

Picture 2 (dark theme)
image

Picture 3
image

Picture 4
image

Picture 5 (dark theme)
image

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by Famozzy**
# Issue #105 📐

- I [Famozzy](https://github.com/Famozzy) have worked for #105

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #105

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

<attach screenshots here>
  
  
  
---

image
image
image
image
image
image

### CODE REVIEW

**Comment by warmachine028** [comment]
change PR title to Issue Name

**Review by warmachine028 — CHANGES_REQUESTED** [review]
make changes in pr title

**Comment by Famozzy** [comment]
changed

**Review by warmachine028 — CHANGES_REQUESTED** [review]
image

can you center align the contents of this card please?

**Comment by Famozzy** [comment]
yeah, i can fix that

**Review by warmachine028 — APPROVED** [review]
changes LGTM

**Pull request merged**
