### PR TITLE
fix: onclick event when click on View Details button

### LINKED ISSUE #458: [BUG 🐞] View Details Button is not working properly
### Description

# Description

* When I click on "View Details" button it scroll me down and stick there, even when I try to scroll up I'm not able scroll. 

### Screenshots

image

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by Jai-Marothiya**
# Issue #458📐

- I [Jai Marothiya](https://github.com/Jai-Marothiya) have worked for #458 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #458

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

<attach screenshots here>
  
  
  
---

### CODE REVIEW

**Comment by warmachine028** [comment]
@Jai-Marothiya how do you justify your contribution to this project? you have just commented a line in a file. Next time please submit a valuable contribution, we here highly believe at quality over quantity.

**Comment by Jai-Marothiya** [comment]
> @Jai-Marothiya how do you justify your contribution to this project? you have just commented a line in a file. Next time please submit a valuable contribution, we here highly believe at quality over quantity.

@warmachine028 - This is not about the amount of contribution I did. Basically I found one bug and if it can fix by commenting one line then what is the problem in it. I know it is not big contribution but if the bug can fix by this then I think its good.

**Comment by warmachine028** [comment]
You have misidentified the bug. It was never a bug, the button redirects user to a new page. You could have instead added a layout for the product details with a dummy data

**Comment by Jai-Marothiya** [comment]
> You have misidentified the bug. It was never a bug, the button redirects user to a new page. You could have instead added a layout for the product details with a dummy data

In that case you have to clarify me first that this is the scenario rather then pointing out someone.

**Comment by warmachine028** [comment]
> > You have misidentified the bug. It was never a bug, the button redirects user to a new page. You could have instead added a layout for the product details with a dummy data
> 
> In that case you have to clarify me first that this is the scenario rather then pointing out someone.

I did not raise the issue since I'm aware of this feature. Whereas when this issue was raised, it was expected that the feature was to be implemented rather than suppressing by commenting out a piece of code.

**Pull request closed without merging**
