### PR TITLE
disabled users from selecting or dragging images

### LINKED ISSUE #43: [FEATURE 💡] Allowing users to select images and drag them is probably not a good idea.
### Description

I want to make so that users can only select text. 

Many websites do this.

It also helps me solve #39 as I am unable to make sure text selection color does not interfere with images.

### Screenshots

_No response_

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by CodeTorso**
This PR closes issue number #43 📐

I [CodeTorso](https://github.com/CodeTorso) have worked on #43 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

This PR helps me working on another issue #39 

## Screenshots 📷
Here are the pictures of changes that I have made 🔽

## Before
Screenshot 2023-09-10 174317

## After
Screenshot 2023-09-10 174355

### CODE REVIEW

**Comment by warmachine028** [comment]
# Hey @CodeTorso, Great to see your enthusiasm towards contributing in Nike
However, Could you please edit the PR template according to the one's closed or merged before. 
It seems really confusing which issue is being worked on or solved.

**Review by warmachine028 — APPROVED** [review]
Changes look neat

**Comment by CodeTorso** [comment]
Hey I have updated the PR to make you better understand. 

Hope you merge it. This PR helps the changed text selection color to better reflect on the website by PR #45 .

**Comment by warmachine028** [comment]
Great

**Comment by CodeTorso** [comment]
Nice

**Pull request merged**
