### PR TITLE
[FIX 🛠️] Cart Add or Subtract Item

### LINKED ISSUE #171: [BUG 🐞] Cart Add or Subtract Item
### Description

Both the '-' and the 'x' buttons reduce the item in the cart. I believe the buttons should be '-' and '+' instead. 

### Screenshots

Here, both - and x subtract the item from the cart.

[Screencast from 2023-10-19 13-29-29.webm](https://github.com/warmachine028/nike/assets/101456741/e689c60d-cf9e-4efe-a0f2-eeb1cbe30eb5)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by shoaib-31**
# Issue #171  📐

- I [Shoaib Akhtar](https://github.com/shoaib-31) have worked for #171 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #171 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

<attach screenshots here>
  
[video.webm](https://github.com/warmachine028/nike/assets/103197883/3ffd0de8-ea93-4e14-9cca-cbda21278aba)

  
  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
@shoaib-31 Great work here, I would suggest just a minor change.
- Add a Trash icon to remove the item from cart
- And don't allow user to go below 1 qty and above 10 qty.

**Comment by shoaib-31** [comment]
@warmachine028 Is it right position of trash can?
[video.webm](https://github.com/warmachine028/nike/assets/103197883/282b63b6-ddef-4f47-8a56-5a0badc01460)

**Comment by warmachine028** [comment]
> @warmachine028 Is it right position of trash can?
> 
>  video.webm

Absolutely, great work

**Comment by shoaib-31** [comment]
I have added restrictions also on plus and minus buttons. Hope, issue is fixed :) @warmachine028

**Review by warmachine028 — APPROVED** [review]

**Pull request merged**
