### PR TITLE
[FIX 🛠️] Shift in Page when select option of Navbar

### LINKED ISSUE #101: Shift in Page when select option of Navbar
### Description

Steps to Reproduce:

Open Website.
Navigate to the Navbar.
Click on any of the Navbar options.
.
.
.
I will be happy to work on this issue.

### Screenshots

_No response_

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by abdulrehmanjaved-1**
# Issue #101 📐

- I [Abdulrehman Javed](https://github.com/abdulrehmanjaved-1) have worked for #101

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #101

## Screenshots 📷

Here are the pictures of changes that I have made 🔽
Screenshot from 2023-10-05 13-07-33

  
  
  
---

### CODE REVIEW

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Complete the PR template
Add the issue name as The PR title
Change BUG 🐞 to FIX 🛠️, refer closed PR titles

**Comment by abdulrehmanjaved-1** [comment]
making it again

**Comment by warmachine028** [comment]
No need to close this PR, you can copy the template from .GitHub directory only

**Comment by abdulrehmanjaved-1** [comment]
Can you tell where is .GitHub directory?

**Comment by warmachine028** [comment]
> Can you tell where is .GitHub directory?

[Here](https://github.com/warmachine028/nike/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by abdulrehmanjaved-1** [comment]
now?

**Review by warmachine028 — COMMENTED** [review]
add Screenshots of the UI where the changes are made, not the Code

**Review by warmachine028 — CHANGES_REQUESTED** [review]
add Screenshots of the UI where the changes are made, not the Code

**Comment by abdulrehmanjaved-1** [comment]
Done

**Pull request merged**
