### PR TITLE
[FEATURE 💡] Menu needs changes

### LINKED ISSUE #112: [FEATURE 💡] Menu needs changes
### Description

- The menu must open over everything, including the navbar
- It also had a slight open animation before, it must be added again.

### Screenshots

image

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by akash0708**
# Issue #112  📐

- I [Akash Bag](https://github.com/akash0708) have worked for #112 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #112 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

hacktonikeani

    
---

### CODE REVIEW

**Review by warmachine028 — COMMENTED** [review]
image

if we scroll down the menu, the things below are also showing, can this be stopped

**Review by warmachine028 — CHANGES_REQUESTED** [review]
image

if we scroll down the menu, the things below are also showing, can this be stopped

**Comment by akash0708** [comment]
@warmachine028 Can you tell me what the problem exactly is? Or in which device it is occurring? I'm not being able to reproduce this bug.

**Comment by warmachine028** [comment]
> @warmachine028 Can you tell me what the problem exactly is? Or in which device it is occurring? I'm not being able to reproduce this bug.

When we open the menu and scroll down, it is scrolling till the end of the page in mobile devices. see Use dev tools in browser to replicate this bug

**Review by warmachine028 — APPROVED** [review]
I believe the current changes can work as a workaround

**Comment by akash0708** [comment]
Can you check it now? I think the issue has been fixed.

**Pull request merged**
