### PR TITLE
[FEATURE 💡] Hamburger menu (not finished)

### PR DESCRIPTION
**Pull request by FranDiSilvestro**
# Issue #1  📐

- I [Franco](https://github.com/FranDiSilvestro) have worked for #1 

[put x to check the boxes]: <> (This is a comment, it will not be included)

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

### CODE REVIEW

**Comment by warmachine028** [comment]
The hamburger menu looks awesome 🚀

**Comment by warmachine028** [comment]
@FranDiSilvestro  Will you be working on this PR or should I merge it?

**Comment by FranDiSilvestro** [comment]
Merge both of it

**Comment by FranDiSilvestro** [comment]
I will do another PR later

**Comment by warmachine028** [comment]
Alright

**Pull request merged**
