### PR TITLE
margin added for cart

### PR DESCRIPTION
**Pull request by vishisht-dubey**
# Issue #<issue number> 📐

- I Vishisht Dubey (https://github.com/vishisht-dubey) have worked for  #143

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #<issuenumber>

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

<attach screenshots here>
  
Screenshot from 2023-10-15 10-58-28

  
  
---

### CODE REVIEW

**Review by AbdullahWins — COMMENTED** [review]
Well Done!

**Comment by vishisht-dubey** [comment]
Hii @AbdullahWins can you please merge this so that it can be counted as a successful PR in hactoberfest.
Thanks

**Comment by warmachine028** [comment]
Hello Contributor,
- Make sure to see all the Closed PRs for the proper PR title and PR template
- Read this issue for the [reason]( https://github.com/warmachine028/nike/issues/151) for delay in PR approvals

**Comment by warmachine028** [comment]
Don't start working on issues without getting assigned to them first

**Pull request closed without merging**
