### PR TITLE
[FEATURE 💡] Add a go to top FAB for Nike

### LINKED ISSUE #53: [FEATURE 💡] Add a go to top FAB for Nike
### Description

- A floating action Button must be added to reach to top of the page on one click.
- This button must only be visible after reaching a certain height in the page from Top.
- The scroll effect must be smooth and not instant.
- It must be overlayed and the position must be at bottom right corner of the screen
- It must be visible for both small screen and large screen devices.

### Screenshots

- This is a reference of a Floating Action Button.
IMG_20230913_121204

### Additional information

- Only use TailwindCSS and refrain from using Inline styles or Plain CSS.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

### PR DESCRIPTION
**Pull request by ayushichoudhary-19**
# Issue https://github.com/warmachine028/nike/issues/53 📐

- I [Ayushi Choudhary](https://github.com/ayushichoudhary-19) have worked for #53 

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #53 

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

image

image

### CODE REVIEW

**Comment by warmachine028** [comment]
Why is the preview not rendering? Is the code okay?

**Comment by warmachine028** [comment]
Screenshot_2023-09-18-14-31-11-980_com android chrome
Please look at the logs

**Comment by ayushichoudhary-19** [comment]
Yes, I have checked, and I've identified an issue in the code. Should I create a new PR? I'm not sure if I can add the commits to this one.

**Comment by warmachine028** [comment]
image

**Comment by ayushichoudhary-19** [comment]
Sorry but I'm not sure how its done, so I am making a new PR.

**Comment by warmachine028** [comment]
It's done

**Comment by warmachine028** [comment]
Good job! Merging it

**Pull request merged**
